---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: controller:latest
    newName: docker.io/spiarh/controller
    newTag: latest2

resources:
  - ../default

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
