#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_file="${repo_root}/deploy/kustomize/rbac/role.yaml"
destination_file="${repo_root}/deploy/helm/garage-s3-operator/templates/clusterrole-manager.yaml"
header="# Code generated by hack/sync-helm-operator.sh. DO NOT EDIT.\n"

if [[ ! -f "${source_file}" ]]; then
  echo "Missing generated RBAC file: ${source_file}" >&2
  exit 1
fi

mkdir -p "$(dirname "${destination_file}")"
printf '%b' "${header}" > "${destination_file}"
cat "${source_file}" >> "${destination_file}"

echo "Synced $(basename "${source_file}") to $(basename "${destination_file}")"
