{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "garage-s3-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garage-s3-operator.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ .Values.serviceMonitor.insecureSkipVerify }}
  selector:
    matchLabels:
      {{- include "garage-s3-operator.selectorLabels" . | nindent 6 }}
{{- end }}
