replicaCount: 1

image:
  repository: controller
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

metricsService:
  enabled: true
  port: 8443

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  insecureSkipVerify: true
