# This rule is not used by the project garage-s3-operator itself.
# It is provided to allow the cluster admin to help manage garagepermissions for users.
#
# Grants read-only access to s3.spiarh.fr resources.
# This role is intended for users who need visibility into these resources
# without garagepermissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: garage-s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: bucket-viewer-role
rules:
- apiGroups:
  - s3.spiarh.fr
  resources:
  - garagebuckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3.spiarh.fr
  resources:
  - garagebuckets/status
  verbs:
  - get
