---
name: release

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

permissions:
  attestations: write
  contents: write
  packages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  OPERATOR_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/garage-s3-operator
  HELM_REPO_BASE: ghcr.io/${{ github.repository_owner }}/helm
  HELM_OPERATOR_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/helm/garage-s3-operator
  HELM_CRDS_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/helm/garage-s3-operator-crds

jobs:
  release:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 #v4.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Operator
      - name: Generate images meta operator
        id: meta-operator
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf #v6.0.0
        with:
          images: ${{ env.OPERATOR_IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Publish multi-arch image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 #v7.0.0
        id: build-push
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: ${{ steps.meta-operator.outputs.tags }}
          labels: ${{ steps.meta-operator.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest@v4.1.0
        with:
          subject-name: ${{ env.OPERATOR_IMAGE_NAME }}
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true

      # Helm Chart CRD
      - name: Generate images meta helm-crds
        id: meta-helm-crds
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf #v6.0.0
        with:
          images: ${{ env.HELM_CRDS_IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Compute Helm chart version
        id: meta-helm-crds-version
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "chart_version=0.0.0-${DOCKER_METADATA_OUTPUT_VERSION}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "chart_version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Unsupported event for Helm chart publishing: ${GITHUB_EVENT_NAME}" >&2
          exit 1

      - name: Publish Helm chart CRD to GHCR
        id: helm-crds
        run: |
          HELM_VERSION=${{ steps.meta-helm-crds-version.outputs.chart_version }}
          PACKAGE_FILE=$(helm package --app-version ${{ steps.meta-helm-crds.outputs.version }} --version "${HELM_VERSION}" deploy/helm/crds | awk -F ': ' '/Successfully packaged chart and saved it to:/{print $2}')
          helm push "${PACKAGE_FILE}" oci://"${HELM_REPO_BASE}" 2> .digest
          DIGEST=$(awk -F "[, ]+" '/Digest/{print $NF}' .digest)
          echo "DIGEST=${DIGEST}" >> $GITHUB_OUTPUT
      - name: Generate artifact attestation for Helm Chart CRD
        uses: actions/attest@v4.1.0
        with:
          subject-name: ${{ env.HELM_CRDS_IMAGE_NAME }}
          subject-digest: ${{ steps.helm-crds.outputs.DIGEST }}
          push-to-registry: true

      # Helm Chart Operator
      - name: Generate images meta helm-operator
        id: meta-helm-operator
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf #v6.0.0
        with:
          images: ${{ env.HELM_OPERATOR_IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Compute Helm chart version
        id: meta-helm-operator-version
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "chart_version=0.0.0-${DOCKER_METADATA_OUTPUT_VERSION}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "chart_version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Unsupported event for Helm chart publishing: ${GITHUB_EVENT_NAME}" >&2
          exit 1
      - name: Publish Helm chart Operator to GHCR
        id: helm-operator
        run: |
          HELM_VERSION=${{ steps.meta-helm-operator-version.outputs.chart_version }}
          yq -i '.image.tag = "${{ steps.meta-helm-operator.outputs.version }}"' deploy/helm/operator/values.yaml
          yq -i '.image.digest = "${{ steps.build-push.outputs.digest }}"' deploy/helm/operator/values.yaml
          PACKAGE_FILE=$(helm package --app-version ${{ steps.meta-helm-operator.outputs.version }} --version "${HELM_VERSION}" deploy/helm/operator | awk -F ': ' '/Successfully packaged chart and saved it to:/{print $2}')
          helm push "${PACKAGE_FILE}" oci://"${HELM_REPO_BASE}" 2> .digest
          DIGEST=$(awk -F "[, ]+" '/Digest/{print $NF}' .digest)
          echo "DIGEST=${DIGEST}" >> $GITHUB_OUTPUT
      - name: Generate artifact attestation for Helm Chart Operator
        uses: actions/attest@v4.1.0
        with:
          subject-name: ${{ env.HELM_OPERATOR_IMAGE_NAME }}
          subject-digest: ${{ steps.helm-operator.outputs.DIGEST }}
          push-to-registry: true
